name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Version in themator.php
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          sed -i "s/Version:     .*/Version:     $VERSION/" themator.php
          sed -i "s/define( 'THEMATOR_VERSION', '.*' );/define( 'THEMATOR_VERSION', '$VERSION' );/" themator.php

      - name: Create Zip
        run: |
          mkdir themator
          rsync -a --exclude='.git' --exclude='.github' --exclude='themator' --exclude='*.zip' ./ themator/
          zip -r themator.zip themator/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: themator.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
